python example_script.py --num 10
python example_script.py --num 15
python example_script.py --num 22
python example_script.py --num 8
python example_script.py --num 30
python example_script.py --num 18
python example_script.py --num 25
python example_script.py --num 12
python example_script.py --num 28
python example_script.py --num 9
python example_script.py --num 20
python example_script.py --num 14
python example_script.py --num 27
python example_script.py --num 11
python example_script.py --num 23
python example_script.py --num 16
python example_script.py --num 29
python example_script.py --num 13
python example_script.py --num 21
python example_script.py --num 17
